### ISSUE TITLE
UnsatisfiedLinkError / SIGSEGV (createSkiaSurface) on Android <= 9 with 9.13.1+

### ISSUE THREAD

**Issue by thorbenprimke** [rive-app/rive-android#350]
### Description

After upgrading from 9.13.0 to 9.13.1 or above, our app crashes on Android 8 and 9 devices due to native lib loading error. 

I traced it down to 9.13.1 and potentially the change from NDK 25 to 27 or the cmake option changes. 
https://github.com/rive-app/rive-android/commit/7da0bfeee57dc2a36ea6ba21811f4820dc198bba#diff-4c32e7b3890f839b96f9fc5057b578eec8a0d6835f4ec94cf084b6093f48fc61R26

Or at least that's the only change in 9.13.1 that looks suspicious to causing any issues. 

### Provide a Repro

Use Rive in an app and open the screen with the rive component on an Android 9 device. Notice that with 9.13.0 it works and with 9.13.1 the app crashes. I can only make it crash when I go to the screen with the component but based on Play Store console / Instabug it might to happen on app launch as well.  

### Expected behavior

Should not crash

#### Screenshots

Crash #1: 
<img width="501" alt="Screenshot 2025-01-07 at 10 23 18 AM" src="https://github.com/user-attachments/assets/bcfcba89-bcd4-40af-a72b-9a341f24e1a6" />
<img width="1007" alt="Screenshot 2025-01-07 at 10 22 35 AM" src="https://github.com/user-attachments/assets/ec309d9e-6185-4348-8238-9340bd682554" />

Crash #2: 
<img width="499" alt="Screenshot 2025-01-07 at 10 23 08 AM" src="https://github.com/user-attachments/assets/348aad53-2aab-4252-b556-bd06f5855b7a" />
<img width="1011" alt="Screenshot 2025-01-07 at 10 22 56 AM" src="https://github.com/user-attachments/assets/d7f440c8-b2e5-45cd-9be6-8f3f57cddac3" />

### Device & Versions

- Device: Broad range of devices - the device count is low because we pushed an update quickly reverting to 9.13.0
<img width="1255" alt="Screenshot 2025-01-07 at 10 25 30 AM" src="https://github.com/user-attachments/assets/eaee7ea3-a891-4090-93fe-b065cf4d7e2a" />

- SDK Level [e.g. Android SDK API Level 30]
26, 27, 28

#### Additional context

The app is targeting / compile SDK is 35.

**Comment by thorbenprimke** [comment]
It's the same as #348. We build out so files with NDK 26. So not sure if this is simply NDK related since the change was upgrading from NDK 25 to 27.

**Comment by raghav09121987** [comment]
we are getting the same issue.

**Comment by aegis123** [comment]
We had also had the UnsatisfiedLinkError when starting rive. Which was caused due to having multiple dependencies which have native libraries

In our case we have both mapbox and rive as a dependency and both try to add libc++_shared.so.
Mapbox uses the ndk23 to compile their native code so libc++_shared.so is not using 16kb page size yet.

We were using:
```kotlin
packagingOptions {
    jniLibs.pickFirsts += setOf("**/libc++_shared.so")
}
```

fix the error
```
* What went wrong:
Execution failed for task ':android:vriendenloterij:mergeAccDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/user/.gradle/caches/8.12.1/transforms/40386025456db6d0cd93126c8a44ec07/transformed/common-24.9.0/jni/arm64-v8a/libc++_shared.so
      - /Users/user/.gradle/caches/8.12.1/transforms/6f1af6f97dcf0effdcb3e9de2c15ce67/transformed/rive-android-9.13.10/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

So it always picks the first .so file which is found so in this case the Mapbox one.

The fix is to ensure all native libraries are compiled with ndk27. For mapbox it was easy since the provide a separate artifact `com.mapbox.maps:android-ndk27` 

So would recommend Rive to revert the change the made in 9.13.1 where they update the NDK which seems a breaking change, not perse for Rive but for other native libraries. and if the want to also build a NDK27 version make a separate artifact. To ensure its backwards compatible and once NDK28 is released the artifacts should be reversed with a specific artifact targeting ndk26 or lower. Since 16kb pages will be enabled by default then.

**Comment by PhilippNowak96** [comment]
Looks like it is solved with `10.x` (tested on `10.0.1`). Can anyone else confirm that as well?

**Comment by jt-gilkeson** [comment]
We're still getting crashes with 10.0.5 on API 23 (6.0) - the crash just changed:
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: no non-static method "Lapp/rive/runtime/kotlin/renderers/RiveArtboardRenderer;.setRendererType(I)V"
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at long app.rive.runtime.kotlin.renderers.Renderer.constructor(boolean, int) (Renderer.kt:-2)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void app.rive.runtime.kotlin.renderers.Renderer.make() (Renderer.kt:61)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void app.rive.runtime.kotlin.RiveTextureView.onAttachedToWindow() (RiveTextureView.kt:53)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void app.rive.runtime.kotlin.RiveAnimationView.onAttachedToWindow() (RiveAnimationView.kt:875)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void android.view.View.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (View.java:14514)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:2843)
2025-04-09 18:21:56.193  6650-6650  art                     com.mudflap.mudflap.develop          A  art/runtime/java_vm_ext.cc:410]   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:2843)
2025-04-0
